#pragma once
#include <raylib.h>
#include "sound.cpp"

namespace tex {
    static Texture2D grass;
    static Texture2D grass2;
    static Texture2D grass3;
    static Texture2D grass4;
    static Texture2D grass_transition;
    static Texture2D grass_transition2;
    static Texture2D water;
    static Texture2D desert;
    static Texture2D desert_transition;
    static Texture2D treasure;
    static Texture2D hill;
    static Texture2D hill2;
    static Texture2D hill3;
    static Texture2D hill4;
    static Texture2D hill_transition;
    static Texture2D hill_transition2;
    static Texture2D hill_outline;
    static Texture2D hill_wedge;
    static Texture2D mountain;
    static Texture2D mountain_transition;
    static Texture2D mountain_transition2;
    static Texture2D human;
    static Texture2D esper;
    static Texture2D scout;
    static Texture2D hero;
    static Texture2D tank;
    static Texture2D datacenter;
    static Texture2D railgun;
    static Texture2D fort;
    static Texture2D fight;
    static Texture2D bison;
    static Texture2D hog;
    static Texture2D wolf;
    static Texture2D hide;
    static Texture2D heal;
    static Texture2D field;
    static Texture2D field_little;
    static Texture2D field_empty;
    static Texture2D mine;
    static Texture2D camp;
    static Texture2D lab;
    static Texture2D warehouse;
    static Texture2D overlay;
    static Texture2D banner;
    static Texture2D blood;
    static Texture2D ghost;
    static Texture2D crater;
    static Texture2D radio;
    static Texture2D lighthouse;
    static Texture2D info;
    static Texture2D oil;
    static Texture2D tree;
    static Texture2D snowman;
    static Texture2D van;
    static Texture2D gear;
    static Texture2D utopia;
    static Texture2D propaganda;
    static Texture2D track;
    static Texture2D rotate;
    static Texture2D flank;
    static Texture2D mind;
    static Texture2D wonder;
    static Texture2D nuclear;
    static Texture2D snipe;
    static Texture2D grit;
    static Texture2D heroics;
    static Texture2D shield;
    static Texture2D hijack;
    static Texture2D tough;
    static Texture2D agile;
    static Texture2D driver;
    static Texture2D gigajoule;
    static Texture2D nerds;
    static Texture2D seafaring;
    static Texture2D discourse;
    static Texture2D central;
    static Texture2D autorepair;
    static Texture2D magnet;
    static Texture2D chart;
    static Texture2D sun;
    static Texture2D reward;
    static Texture2D earth;
    static Texture2D research;
    static Texture2D pristine;
    static Texture2D rat;
    static Texture2D roomba;
    static Texture2D curio;
    static Texture2D rock;
    static Texture2D trenches;
    static Texture2D ownership;
    static Texture2D unstable;
    static Texture2D bioweapon;
    static Texture2D victory;
    static Texture2D defeat;
    static Texture2D hovercraft;
    static Texture2D engine;
    static Texture2D superiority;
    static Texture2D vroom;
    static Texture2D revup;
    static Texture2D cat;
    static Texture2D command;
    static Texture2D homunculi;
    static Texture2D kraken;
}


void load() {

    tex::grass = LoadTexture("data/grass.png");
    tex::grass2 = LoadTexture("data/grass2.png");
    tex::grass3 = LoadTexture("data/grass3.png");
    tex::grass4 = LoadTexture("data/grass4.png");
    tex::grass_transition = LoadTexture("data/grass_transition.png");
    tex::grass_transition2 = LoadTexture("data/grass_transition2.png");
    tex::treasure  = LoadTexture("data/treasure.png");
    tex::hill  = LoadTexture("data/hill3.png");
    tex::hill2 = LoadTexture("data/hill2.png");
    tex::hill3 = LoadTexture("data/hill.png");
    tex::hill4 = LoadTexture("data/hill4.png");
    tex::hill_transition = LoadTexture("data/hill_transition.png");
    tex::hill_transition2 = LoadTexture("data/hill_transition2.png");
    tex::hill_outline = LoadTexture("data/hill_outline.png");
    tex::hill_wedge = LoadTexture("data/hill_wedge.png");
    tex::mountain = LoadTexture("data/mountain.png");
    tex::mountain_transition = LoadTexture("data/mountain_transition.png");
    tex::mountain_transition2 = LoadTexture("data/mountain_transition2.png");
    tex::tree = LoadTexture("data/tree.png");
    tex::desert = LoadTexture("data/desert.png");
    tex::water = LoadTexture("data/water.png");
    tex::desert_transition = LoadTexture("data/desert_transition.png");
    tex::human = LoadTexture("data/human.png");
    tex::esper = LoadTexture("data/esper.png");
    tex::scout = LoadTexture("data/scout.png");
    tex::hero = LoadTexture("data/hero.png");
    tex::tank = LoadTexture("data/tank.png");
    tex::van = LoadTexture("data/van.png");
    tex::gear = LoadTexture("data/gear.png");
    tex::utopia = LoadTexture("data/utopia.png");
    tex::propaganda = LoadTexture("data/propaganda.png");
    tex::track = LoadTexture("data/track.png");
    tex::rotate = LoadTexture("data/rotate.png");
    tex::flank = LoadTexture("data/flank.png");
    tex::mind = LoadTexture("data/hivemind.png");
    tex::wonder = LoadTexture("data/wonder.png");
    tex::nuclear = LoadTexture("data/nuclear.png");
    tex::snipe = LoadTexture("data/snipe.png");
    tex::grit = LoadTexture("data/grit.png");
    tex::heroics = LoadTexture("data/heroics.png");
    tex::shield = LoadTexture("data/shield.png");
    tex::hijack = LoadTexture("data/hijack.png");
    tex::tough = LoadTexture("data/tough.png");
    tex::agile = LoadTexture("data/agile.png");
    tex::driver = LoadTexture("data/driver.png");
    tex::gigajoule = LoadTexture("data/gigajoule.png");
    tex::nerds = LoadTexture("data/nerds.png");
    tex::seafaring = LoadTexture("data/seafaring.png");
    tex::discourse = LoadTexture("data/discourse.png");
    tex::central = LoadTexture("data/central.png");
    tex::autorepair = LoadTexture("data/autorepair.png");
    tex::magnet = LoadTexture("data/magnet.png");
    tex::chart = LoadTexture("data/chart.png");
    tex::pristine = LoadTexture("data/pristine.png");
    tex::sun = LoadTexture("data/sun.png");
    tex::reward = LoadTexture("data/reward.png");
    tex::earth = LoadTexture("data/earth.png");
    tex::research = LoadTexture("data/research.png");
    tex::snowman = LoadTexture("data/snowman.png");
    tex::railgun = LoadTexture("data/railgun.png");
    tex::fort = LoadTexture("data/fort.png");
    tex::fight = LoadTexture("data/fight.png");
    tex::hide = LoadTexture("data/hide.png");
    tex::rat = LoadTexture("data/rat.png");
    tex::roomba = LoadTexture("data/roomba.png");
    tex::bison = LoadTexture("data/bison.png");
    tex::hog = LoadTexture("data/hog.png");
    tex::wolf = LoadTexture("data/wolf.png");
    tex::heal = LoadTexture("data/heal.png");
    tex::field = LoadTexture("data/field.png");
    tex::field_empty = LoadTexture("data/field_empty.png");
    tex::field_little = LoadTexture("data/field_little.png");
    tex::mine = LoadTexture("data/mine.png");
    tex::camp = LoadTexture("data/camp.png");
    tex::lab = LoadTexture("data/lab.png");;
    tex::warehouse = LoadTexture("data/warehouse.png");
    tex::curio = LoadTexture("data/curio.png");
    tex::rock = LoadTexture("data/rock.png");
    tex::blood = LoadTexture("data/blood.png");
    tex::ghost = LoadTexture("data/ghost.png");
    tex::crater = LoadTexture("data/crater.png");
    tex::radio = LoadTexture("data/radio.png");
    tex::lighthouse = LoadTexture("data/lighthouse.png");
    tex::oil = LoadTexture("data/oil.png");
    tex::datacenter = LoadTexture("data/datacenter.png");
    tex::info = LoadTexture("data/info.png");
    tex::overlay = LoadTexture("data/overlay.png");
    tex::banner = LoadTexture("data/banner.png");
    tex::banner = LoadTexture("data/banner.png");
    tex::trenches = LoadTexture("data/trenches.png");
    tex::ownership = LoadTexture("data/ownership.png");
    tex::unstable = LoadTexture("data/unstable.png");
    tex::bioweapon = LoadTexture("data/bioweapon.png");
    tex::victory = LoadTexture("data/victory.png");
    tex::defeat = LoadTexture("data/defeat.png");
    tex::hovercraft = LoadTexture("data/hovercraft.png");
    tex::engine = LoadTexture("data/engine.png");
    tex::superiority = LoadTexture("data/superiority.png");
    tex::vroom = LoadTexture("data/vroom.png");
    tex::revup = LoadTexture("data/revup.png");
    tex::cat = LoadTexture("data/cat.png");
    tex::command = LoadTexture("data/command.png");
    tex::homunculi= LoadTexture("data/homunculi.png");
    tex::kraken= LoadTexture("data/kraken.png");

    sound::gun.Load("data/gun.ogg", 24);
    sound::boom.Load("data/boom.ogg", 5);
    sound::explosion.Load("data/explosion.ogg", 10);
    sound::damage.Load("data/damage.wav", 10);
    sound::dead.Load("data/dead.ogg", 10);
    sound::ohm.Load("data/ohm.ogg", 5);
    sound::moo.Load("data/moo.wav", 10);
    sound::noise.Load("data/noise.wav", 5);
    sound::notify.Load("data/notify.ogg", 5);
    sound::water.Load("data/water.ogg", 5);
    sound::select = LoadSound("data/select.wav");
    sound::select2 = LoadSound("data/select2.wav");
    sound::bg = LoadMusicStream("data/track.ogg");
}


void unload() {
    UnloadTexture(tex::gear);
    UnloadTexture(tex::sun);
    UnloadTexture(tex::reward);
    UnloadTexture(tex::research);
    UnloadTexture(tex::utopia);
    UnloadTexture(tex::propaganda);
    UnloadTexture(tex::track);
    UnloadTexture(tex::grass);
    UnloadTexture(tex::grass2);
    UnloadTexture(tex::grass3);
    UnloadTexture(tex::grass4);
    UnloadTexture(tex::grass_transition);
    UnloadTexture(tex::grass_transition2);
    UnloadTexture(tex::treasure);
    UnloadTexture(tex::hill);
    UnloadTexture(tex::hill2);
    UnloadTexture(tex::hill3);
    UnloadTexture(tex::hill4);
    UnloadTexture(tex::hill_transition);
    UnloadTexture(tex::hill_transition2);
    UnloadTexture(tex::hill_outline);
    UnloadTexture(tex::hill_wedge);
    UnloadTexture(tex::desert);
    UnloadTexture(tex::desert_transition);
    UnloadTexture(tex::mountain);
    UnloadTexture(tex::mountain_transition);
    UnloadTexture(tex::mountain_transition2);
    UnloadTexture(tex::human);
    UnloadTexture(tex::esper);
    UnloadTexture(tex::scout);
    UnloadTexture(tex::hero);
    UnloadTexture(tex::tank);
    UnloadTexture(tex::van);
    UnloadTexture(tex::snowman);
    UnloadTexture(tex::field);
    UnloadTexture(tex::field_little);
    UnloadTexture(tex::field_empty);
    UnloadTexture(tex::heal);
    UnloadTexture(tex::camp);
    UnloadTexture(tex::lab);
    UnloadTexture(tex::fight);
    UnloadTexture(tex::blood);
    UnloadTexture(tex::bison);
    UnloadTexture(tex::hog);
    UnloadTexture(tex::rat);
    UnloadTexture(tex::roomba);
    UnloadTexture(tex::wolf);
    UnloadTexture(tex::warehouse);
    UnloadTexture(tex::curio);
    UnloadTexture(tex::rock);
    UnloadTexture(tex::ghost);
    UnloadTexture(tex::crater);
    UnloadTexture(tex::radio);
    UnloadTexture(tex::lighthouse);
    UnloadTexture(tex::vroom);
    UnloadTexture(tex::revup);
    UnloadTexture(tex::cat);
    UnloadTexture(tex::command);
    UnloadTexture(tex::homunculi);
    UnloadTexture(tex::kraken);

    UnloadTexture(tex::oil);
    UnloadTexture(tex::datacenter);
    UnloadTexture(tex::info);
    UnloadTexture(tex::overlay);
    UnloadTexture(tex::railgun);
    UnloadTexture(tex::fort);
    UnloadTexture(tex::mine);
    UnloadTexture(tex::tree);
    UnloadTexture(tex::water);
    UnloadTexture(tex::earth);
    UnloadTexture(tex::rotate);
    UnloadTexture(tex::flank);
    UnloadTexture(tex::mind);
    UnloadTexture(tex::wonder);
    UnloadTexture(tex::nuclear);
    UnloadTexture(tex::snipe);
    UnloadTexture(tex::grit);
    UnloadTexture(tex::heroics);
    UnloadTexture(tex::shield);
    UnloadTexture(tex::hijack);
    UnloadTexture(tex::tough);
    UnloadTexture(tex::agile);
    UnloadTexture(tex::driver);
    UnloadTexture(tex::gigajoule);
    UnloadTexture(tex::nerds);
    UnloadTexture(tex::seafaring);
    UnloadTexture(tex::discourse);
    UnloadTexture(tex::central);
    UnloadTexture(tex::autorepair);
    UnloadTexture(tex::magnet);
    UnloadTexture(tex::chart);
    UnloadTexture(tex::pristine);
    UnloadTexture(tex::trenches);
    UnloadTexture(tex::ownership);
    UnloadTexture(tex::unstable);
    UnloadTexture(tex::bioweapon);
    UnloadTexture(tex::victory);
    UnloadTexture(tex::defeat);
    UnloadTexture(tex::hovercraft);
    UnloadTexture(tex::engine);
    UnloadTexture(tex::superiority);
    UnloadTexture(tex::vroom);
    UnloadTexture(tex::revup);
    UnloadTexture(tex::cat);

    sound::boom.Unload();
    sound::explosion.Unload();
    sound::gun.Unload();
    sound::damage.Unload();
    sound::dead.Unload();
    sound::ohm.Unload();
    sound::moo.Unload();
    sound::noise.Unload();
    sound::notify.Unload();
    sound::water.Unload();
    UnloadSound(sound::select);
    UnloadSound(sound::select2);
    CloseAudioDevice();
    CloseWindow();
}